{{- if eq .Values.global.backupType "oneByOne" }}
{{- if empty .Values.oneByOne.dbDataSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pg-backup.name" . }}-db-data
  labels: {{ include "pg-backup.labels" . | nindent 4 }}
  namespace: {{ include "pg-backup.namespace" . }}
data:
  creds.json: {{ .Values.oneByOne.dbData | toJson | b64enc }}
type: Opaque

{{ end -}}
{{ end -}}