apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pg-backup.name" . }}-pg-backup-config
  labels: {{ include "pg-backup.labels" . | nindent 4 }}
  namespace: {{ include "pg-backup.namespace" . }}
data:
  DB_HOST: {{ required "hostname address is essential!" .Values.hostname | quote }}
  DB_PORT: {{ required "port number is essential!" .Values.port | quote }}
  TEAMS_NOTIFICATION: {{ required "teams notification must be enabled or not?!" .Values.global.teamsNotification | quote }}
{{- if .Values.global.rotation }}
  DAYS_TO_KEEP: {{ .Values.global.rotation_config.dayOfWeekToKeep | quote }}
  DAY_OF_WEEK_TO_KEEP: {{ .Values.global.rotation_config.dayOfWeekToKeep | quote }}
  WEEKS_TO_KEEP: {{ .Values.global.rotation_config.daysToKeep | quote }}
{{- end -}}
{{- if .Values.global.teamsNotification }}
  FAILED_TEAMS_URL: {{ .Values.global.failedTeamsURL | quote }}
  SUCCEEDED_TEAMS_URL: {{  .Values.global.succeededTeamsURL | quote }}
{{ end -}}