name: Backup-zen Docker Image CI

on:
  push:
    tags:
      - '*'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push PostgreSQL-Backup-Zen
        uses: docker/build-push-action@v4
        with:
          context: ./docker/pg
          file: ./docker/pg/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pg:$GITHUB_REF_NAME
      -
        name: Build and push MongoDB-Backup-Zen
        uses: docker/build-push-action@v4
        with:
          context: ./docker/mongo
          file: ./docker/mongo/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mongo:$GITHUB_REF_NAME
      -
        name: Build and push MySQL-Backup-Zen
        uses: docker/build-push-action@v4
        with:
          context: ./docker/mysql
          file: ./docker/mysql/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mysql:$GITHUB_REF_NAME
